//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. To update the generation of this file, modify and re-run Unity.Mathematics.Fixed.CodeGen.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.IL2CPP.CompilerServices;
using static Unity.Mathematics.math;

#pragma warning disable 0660, 0661

namespace Unity.Mathematics.Fixed
{
    /// <summary>A 2 component vector of ulongs.</summary>
    [DebuggerTypeProxy(typeof(ulong2.DebuggerProxy))]
    [System.Serializable]
    [Il2CppEagerStaticClassConstruction]
    public partial struct ulong2 : System.IEquatable<ulong2>, IFormattable
    {
        /// <summary>x component of the vector.</summary>
        public ulong x;
        /// <summary>y component of the vector.</summary>
        public ulong y;

        /// <summary>ulong2 zero value.</summary>
        public static readonly ulong2 zero;

        /// <summary>Constructs a ulong2 vector from two ulong values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ulong2(ulong x, ulong y)
        {
            this.x = x;
            this.y = y;
        }

        /// <summary>Constructs a ulong2 vector from a ulong2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ulong2(ulong2 xy)
        {
            this.x = xy.x;
            this.y = xy.y;
        }

        /// <summary>Constructs a ulong2 vector from a single ulong value by assigning it to every component.</summary>
        /// <param name="v">ulong to convert to ulong2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ulong2(ulong v)
        {
            this.x = v;
            this.y = v;
        }


        /// <summary>Implicitly converts a single ulong value to a ulong2 vector by assigning it to every component.</summary>
        /// <param name="v">ulong to convert to ulong2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ulong2(ulong v) { return new ulong2(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise multiplication.</param>
        /// <returns>ulong2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator * (ulong2 lhs, ulong2 rhs) { return new ulong2 (lhs.x * rhs.x, lhs.y * rhs.y); }

        /// <summary>Returns the result of a componentwise multiplication operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise multiplication.</param>
        /// <returns>ulong2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator * (ulong2 lhs, ulong rhs) { return new ulong2 (lhs.x * rhs, lhs.y * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise multiplication.</param>
        /// <returns>ulong2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator * (ulong lhs, ulong2 rhs) { return new ulong2 (lhs * rhs.x, lhs * rhs.y); }


        /// <summary>Returns the result of a componentwise addition operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise addition.</param>
        /// <returns>ulong2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator + (ulong2 lhs, ulong2 rhs) { return new ulong2 (lhs.x + rhs.x, lhs.y + rhs.y); }

        /// <summary>Returns the result of a componentwise addition operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise addition.</param>
        /// <returns>ulong2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator + (ulong2 lhs, ulong rhs) { return new ulong2 (lhs.x + rhs, lhs.y + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise addition.</param>
        /// <returns>ulong2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator + (ulong lhs, ulong2 rhs) { return new ulong2 (lhs + rhs.x, lhs + rhs.y); }


        /// <summary>Returns the result of a componentwise subtraction operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise subtraction.</param>
        /// <returns>ulong2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator - (ulong2 lhs, ulong2 rhs) { return new ulong2 (lhs.x - rhs.x, lhs.y - rhs.y); }

        /// <summary>Returns the result of a componentwise subtraction operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise subtraction.</param>
        /// <returns>ulong2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator - (ulong2 lhs, ulong rhs) { return new ulong2 (lhs.x - rhs, lhs.y - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise subtraction.</param>
        /// <returns>ulong2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator - (ulong lhs, ulong2 rhs) { return new ulong2 (lhs - rhs.x, lhs - rhs.y); }


        /// <summary>Returns the result of a componentwise division operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise division.</param>
        /// <returns>ulong2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator / (ulong2 lhs, ulong2 rhs) { return new ulong2 (lhs.x / rhs.x, lhs.y / rhs.y); }

        /// <summary>Returns the result of a componentwise division operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise division.</param>
        /// <returns>ulong2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator / (ulong2 lhs, ulong rhs) { return new ulong2 (lhs.x / rhs, lhs.y / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise division.</param>
        /// <returns>ulong2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator / (ulong lhs, ulong2 rhs) { return new ulong2 (lhs / rhs.x, lhs / rhs.y); }


        /// <summary>Returns the result of a componentwise modulus operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise modulus.</param>
        /// <returns>ulong2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator % (ulong2 lhs, ulong2 rhs) { return new ulong2 (lhs.x % rhs.x, lhs.y % rhs.y); }

        /// <summary>Returns the result of a componentwise modulus operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise modulus.</param>
        /// <returns>ulong2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator % (ulong2 lhs, ulong rhs) { return new ulong2 (lhs.x % rhs, lhs.y % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise modulus.</param>
        /// <returns>ulong2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator % (ulong lhs, ulong2 rhs) { return new ulong2 (lhs % rhs.x, lhs % rhs.y); }


        /// <summary>Returns the result of a componentwise increment operation on a ulong2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise increment.</param>
        /// <returns>ulong2 result of the componentwise increment.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator ++ (ulong2 val) { return new ulong2 (++val.x, ++val.y); }


        /// <summary>Returns the result of a componentwise decrement operation on a ulong2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise decrement.</param>
        /// <returns>ulong2 result of the componentwise decrement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator -- (ulong2 val) { return new ulong2 (--val.x, --val.y); }


        /// <summary>Returns the result of a componentwise less than operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator < (ulong2 lhs, ulong2 rhs) { return new bool2 (lhs.x < rhs.x, lhs.y < rhs.y); }

        /// <summary>Returns the result of a componentwise less than operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator < (ulong2 lhs, ulong rhs) { return new bool2 (lhs.x < rhs, lhs.y < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator < (ulong lhs, ulong2 rhs) { return new bool2 (lhs < rhs.x, lhs < rhs.y); }


        /// <summary>Returns the result of a componentwise less or equal operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator <= (ulong2 lhs, ulong2 rhs) { return new bool2 (lhs.x <= rhs.x, lhs.y <= rhs.y); }

        /// <summary>Returns the result of a componentwise less or equal operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator <= (ulong2 lhs, ulong rhs) { return new bool2 (lhs.x <= rhs, lhs.y <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator <= (ulong lhs, ulong2 rhs) { return new bool2 (lhs <= rhs.x, lhs <= rhs.y); }


        /// <summary>Returns the result of a componentwise greater than operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator > (ulong2 lhs, ulong2 rhs) { return new bool2 (lhs.x > rhs.x, lhs.y > rhs.y); }

        /// <summary>Returns the result of a componentwise greater than operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator > (ulong2 lhs, ulong rhs) { return new bool2 (lhs.x > rhs, lhs.y > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator > (ulong lhs, ulong2 rhs) { return new bool2 (lhs > rhs.x, lhs > rhs.y); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator >= (ulong2 lhs, ulong2 rhs) { return new bool2 (lhs.x >= rhs.x, lhs.y >= rhs.y); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator >= (ulong2 lhs, ulong rhs) { return new bool2 (lhs.x >= rhs, lhs.y >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator >= (ulong lhs, ulong2 rhs) { return new bool2 (lhs >= rhs.x, lhs >= rhs.y); }


        /// <summary>Returns the result of a componentwise unary plus operation on a ulong2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary plus.</param>
        /// <returns>ulong2 result of the componentwise unary plus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 operator + (ulong2 val) { return new ulong2 (+val.x, +val.y); }


        /// <summary>Returns the result of a componentwise equality operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator == (ulong2 lhs, ulong2 rhs) { return new bool2 (lhs.x == rhs.x, lhs.y == rhs.y); }

        /// <summary>Returns the result of a componentwise equality operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator == (ulong2 lhs, ulong rhs) { return new bool2 (lhs.x == rhs, lhs.y == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator == (ulong lhs, ulong2 rhs) { return new bool2 (lhs == rhs.x, lhs == rhs.y); }


        /// <summary>Returns the result of a componentwise not equal operation on two ulong2 vectors.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator != (ulong2 lhs, ulong2 rhs) { return new bool2 (lhs.x != rhs.x, lhs.y != rhs.y); }

        /// <summary>Returns the result of a componentwise not equal operation on a ulong2 vector and a ulong value.</summary>
        /// <param name="lhs">Left hand side ulong2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side ulong to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator != (ulong2 lhs, ulong rhs) { return new bool2 (lhs.x != rhs, lhs.y != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a ulong value and a ulong2 vector.</summary>
        /// <param name="lhs">Left hand side ulong to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side ulong2 to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2 operator != (ulong lhs, ulong2 rhs) { return new bool2 (lhs != rhs.x, lhs != rhs.y); }




        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 xyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(x, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong4 yyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong4(y, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 xxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 xxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 xyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 xyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 yxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 yxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 yyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong3 yyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong3(y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong2 xx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong2(x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong2 xy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong2(x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong2 yx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong2(y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ulong2 yy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new ulong2(y, y); }
        }



        /// <summary>Returns the ulong element at a specified index.</summary>
        unsafe public ulong this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (ulong2* array = &this) { return ((ulong*)array)[index]; }
            }
            set
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (ulong* array = &x) { array[index] = value; }
            }
        }

        /// <summary>Returns true if the ulong2 is equal to a given ulong2, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(ulong2 rhs) { return x == rhs.x && y == rhs.y; }

        /// <summary>Returns true if the ulong2 is equal to a given ulong2, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is ulong2 converted && Equals(converted); }


        /// <summary>Returns a string representation of the ulong2.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("ulong2({0}f, {1}f)", x, y);
        }

        /// <summary>Returns a string representation of the ulong2 using a specified format and culture-specific format information.</summary>
        /// <param name="format">Format string to use during string formatting.</param>
        /// <param name="formatProvider">Format provider to use during string formatting.</param>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("ulong2({0}f, {1}f)", ((ulong)x).ToString(format, formatProvider), ((ulong)y).ToString(format, formatProvider));
        }

        internal sealed class DebuggerProxy
        {
            public ulong x;
            public ulong y;
            public DebuggerProxy(ulong2 v)
            {
                x = v.x;
                y = v.y;
            }
        }

    }

    public static partial class math
    {
        /// <summary>Returns a ulong2 vector constructed from two ulong values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        /// <returns>ulong2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 ulong2(ulong x, ulong y) { return new ulong2(x, y); }

        /// <summary>Returns a ulong2 vector constructed from a ulong2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        /// <returns>ulong2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 ulong2(ulong2 xy) { return new ulong2(xy); }

        /// <summary>Returns a ulong2 vector constructed from a single ulong value by assigning it to every component.</summary>
        /// <param name="v">ulong to convert to ulong2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong2 ulong2(ulong v) { return new ulong2(v); }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint2 uint2(ulong2 v) { return unchecked(new uint2((uint)v.x,(uint)v.y)); }
    }
}
